name: publish

on:
  release:
    types: [created]
  # support manual release in case something goes wrong and needs to be repeated or tested
  workflow_dispatch:
    inputs:
      tag:
        description: tag that needs to publish
        type: string
        required: true
      prerelease:
        required: false
        description: if true, it will use the version <version>-<branch>.0
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build

        # publish package
      - if: ${{ !inputs.prerelease }}
        name: Release
        run: sf-release npm:package:release --githubtag ${{ inputs.tag}} --no-install --npmtag ${{ inputs.tag }}
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        # publish prerelease package
      - if: ${{ inputs.prerelease }}
        name: PreRelease
        run: sf-release npm:package:release --githubtag ${{ inputs.tag}} --no-install --npmtag ${{ inputs.tag }} --prerelease ${{ github.ref_name}}
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

